embedding_model: 
  provider: "fastembedding"
  model_name : "BAAI/bge-small-en-v1.5"

retriever:
  search_type: "mmr"
  top_k: 3

llm:
  provider: "langchain_groq"
  model: "openai/gpt-oss-120b"
  temperature: 0.1
  max_tokens: 2048

reranker:
  model_name: "rank-T5-flan"
  top_k: 3
  cache_dir: null


